version: '2'
services:
  postgres:
    image: postgres:9.6.3
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_USER=runner
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=myapp_test
    volumes:
      - ./data/postgres:/var/lib/postgresql/data